# Generated by Django 4.2.4 on 2023-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заполнения')),
            ],
        ),
        migrations.CreateModel(
            name='RetailValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitate', models.CharField(blank=True, default='тн', max_length=10, null=True, verbose_name='Еденица измерения')),
                ('typeOil', models.CharField(max_length=25, verbose_name='Тип топлива')),
                ('summMonth', models.FloatField(max_length=10, verbose_name='Показатели за месяц')),
                ('summQuarter', models.FloatField(max_length=10, verbose_name='Сумма квартал')),
                ('summYear', models.FloatField(max_length=10, verbose_name='Сумма за год')),
                ('summFactMonth', models.FloatField(max_length=10, verbose_name='Показатели факт за месяц')),
                ('summFactQuarter', models.FloatField(max_length=10, verbose_name='Сумма факт квартал')),
                ('summFactYear', models.FloatField(max_length=10, verbose_name='Сумма факт за год')),
                ('summFactBeforeMonth', models.FloatField(max_length=10, verbose_name='Показатели предыдущий месяц')),
                ('date', models.DateField(verbose_name='Дата выгрузки')),
            ],
            options={
                'verbose_name': 'Розница объем',
                'verbose_name_plural': 'Розница объемы',
            },
        ),
        migrations.CreateModel(
            name='SmallOpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitate', models.CharField(blank=True, default='тн', max_length=10, null=True, verbose_name='Еденица измерения')),
                ('typeOil', models.CharField(max_length=25, verbose_name='Тип топлива')),
                ('summMonth', models.FloatField(max_length=10, verbose_name='Показатели за месяц')),
                ('summQuarter', models.FloatField(max_length=10, verbose_name='Сумма квартал')),
                ('summYear', models.FloatField(max_length=10, verbose_name='Сумма за год')),
                ('summFactMonth', models.FloatField(max_length=10, verbose_name='Показатели факт за месяц')),
                ('summFactQuarter', models.FloatField(max_length=10, verbose_name='Сумма факт квартал')),
                ('summFactYear', models.FloatField(max_length=10, verbose_name='Сумма факт за год')),
                ('summFactBeforeMonth', models.FloatField(max_length=10, verbose_name='Показатели предыдущий месяц')),
                ('date', models.DateField(verbose_name='Дата выгрузки')),
            ],
            options={
                'verbose_name': 'Малый отп',
                'verbose_name_plural': 'Малые опты',
            },
        ),
    ]
