# Generated by Django 4.2.4 on 2023-10-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заполнения')),
            ],
        ),
        migrations.CreateModel(
            name='FuelBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(blank=True, max_length=100, verbose_name='Склад')),
                ('fuel', models.CharField(max_length=20, verbose_name='Номенклатура')),
                ('balance', models.FloatField(verbose_name='Остаток')),
                ('owner', models.CharField(max_length=255, verbose_name='Владелец')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'Базы',
            },
        ),
        migrations.CreateModel(
            name='Mony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitate', models.CharField(max_length=10, verbose_name='Еденица измерения')),
                ('summDay', models.FloatField(verbose_name='Сумма день')),
                ('owner', models.CharField(max_length=150, verbose_name='Организация')),
                ('typeSela', models.CharField(max_length=50, verbose_name='Вид продажи')),
                ('summMonth', models.FloatField(verbose_name='Сумма месяц')),
                ('summYear', models.FloatField(verbose_name='Сумма год')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Деньги',
                'verbose_name_plural': 'Деньги',
            },
        ),
        migrations.CreateModel(
            name='RetailValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitate', models.CharField(blank=True, default='тн', max_length=10, null=True, verbose_name='Еденица измерения')),
                ('typeOil', models.CharField(blank=True, max_length=25, verbose_name='Тип топлива')),
                ('summMonth', models.FloatField(blank=True, max_length=20, verbose_name='План месяц')),
                ('summQuarter', models.FloatField(blank=True, max_length=20, verbose_name='План квартал')),
                ('summYear', models.FloatField(blank=True, max_length=20, verbose_name='План год')),
                ('summFactMonth', models.FloatField(blank=True, max_length=20, verbose_name='Показатели факт за месяц')),
                ('summFactQuarter', models.FloatField(blank=True, max_length=20, verbose_name='Сумма факт квартал')),
                ('summFactYear', models.FloatField(blank=True, max_length=20, verbose_name='Сумма факт за год')),
                ('summFactBeforeMonth', models.FloatField(blank=True, max_length=20, verbose_name='Показатели предыдущий месяц')),
                ('summFactDay', models.FloatField(blank=True, max_length=20, verbose_name='Факт за день')),
                ('summDactMonthBeforeYear', models.FloatField(blank=True, max_length=20, verbose_name='Факт месяц предыдущего года')),
                ('date', models.DateField(verbose_name='Дата выгрузки')),
            ],
            options={
                'verbose_name': 'Розница объем',
                'verbose_name_plural': 'Розница объемы',
            },
        ),
        migrations.CreateModel(
            name='SmallOpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitate', models.CharField(blank=True, default='тн', max_length=10, null=True, verbose_name='Еденица измерения')),
                ('typeOil', models.CharField(blank=True, max_length=25, verbose_name='Тип топлива')),
                ('summMonth', models.FloatField(blank=True, max_length=20, verbose_name='План за месяц')),
                ('summQuarter', models.FloatField(blank=True, max_length=20, verbose_name='План квартал')),
                ('summYear', models.FloatField(blank=True, max_length=20, verbose_name='План на год')),
                ('summFactMonth', models.FloatField(blank=True, max_length=20, verbose_name='Показатели факт за месяц')),
                ('summFactQuarter', models.FloatField(blank=True, max_length=20, verbose_name='Сумма факт квартал')),
                ('summFactYear', models.FloatField(blank=True, max_length=20, verbose_name='Сумма факт за год')),
                ('summFactBeforeMonth', models.FloatField(blank=True, max_length=20, verbose_name='Показатели предыдущий месяц')),
                ('summFactDay', models.FloatField(blank=True, max_length=20, verbose_name='Факт за день')),
                ('summDactMonthBeforeYear', models.FloatField(blank=True, max_length=20, verbose_name='Факт месяц предыдущего года')),
                ('date', models.DateField(verbose_name='Дата выгрузки')),
            ],
            options={
                'verbose_name': 'Малый отп',
                'verbose_name_plural': 'Малые опты',
            },
        ),
    ]
